# This file was generated by GoReleaser. DO NOT EDIT.
class Qbec < Formula
  desc "Qbec (pronounced like the Canadian province) is a CLI tool that allows you to create Kubernetes objects on multiple Kubernetes clusters or namespaces configured correctly for the target environment in question."
  homepage "https://qbec.io/"
  version "0.12.1-rogii"
  bottle :unneeded

  if OS.mac?
    url "https://rogii-sre-dist-pub.s3.amazonaws.com/qbec/qbec-0.12.1-rogii-darwin-amd64.tar.gz"
    sha256 "878ac5c28d427eeba4e2e6790068d1317f64688e55fd11cf1e890a6500ace59f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://rogii-sre-dist-pub.s3.amazonaws.com/qbec/qbec-0.12.1-rogii-linux-amd64.tar.gz"
      sha256 "60eedd5fdbbcb77b4299793738360780c0b3b194bef23c6c4ff566dc5097a98e"
    end
  end

  def install
    bin.install ["qbec", "jsonnet-qbec"]
  end

  test do
    system "#{bin}/qbec version"
  end
end
