# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qbec < Formula
  desc "Qbec (pronounced like the Canadian province) is a CLI tool that allows you to create Kubernetes objects on multiple Kubernetes clusters or namespaces configured correctly for the target environment in question."
  homepage "https://qbec.io/"
  version "0.15.2-1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://rogii-sre-dist-pub.s3.amazonaws.com/qbec/qbec-0.15.2-1-darwin-arm64.tar.gz"
      sha256 "86425e46b1f087833dea38f70d5a683cc7439c1f382f67024bde37ea3f2301df"

      def install
        bin.install ["qbec", "jsonnet-qbec"]
      end
    end
    if Hardware::CPU.intel?
      url "https://rogii-sre-dist-pub.s3.amazonaws.com/qbec/qbec-0.15.2-1-darwin-amd64.tar.gz"
      sha256 "3018a05d29c9939fa37cf973e612eb52590f3e3b1774eba5261727adcc90ea54"

      def install
        bin.install ["qbec", "jsonnet-qbec"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://rogii-sre-dist-pub.s3.amazonaws.com/qbec/qbec-0.15.2-1-linux-arm64.tar.gz"
      sha256 "fd2aa8d9ac43e1a8201a274cbfea70831c56c2817593f5970a1a86248f5800a3"

      def install
        bin.install ["qbec", "jsonnet-qbec"]
      end
    end
    if Hardware::CPU.intel?
      url "https://rogii-sre-dist-pub.s3.amazonaws.com/qbec/qbec-0.15.2-1-linux-amd64.tar.gz"
      sha256 "419e15062f9d3c80e231b53f20b92043e436c61fe093857c0bbfb5757e64a870"

      def install
        bin.install ["qbec", "jsonnet-qbec"]
      end
    end
  end

  test do
    system "#{bin}/qbec version"
  end
end
